{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intens-cloud-managament-daemon.fullname" . }}-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
---
{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intens-cloud-managament-daemon.fullname" . }}-password
type: Opaque
data:
  keycloak-password: {{ .Values.keycloak.password | b64enc }}
{{ end }}
