# Default values for intens-cloud-managament-daemon.

replicaCount: 1

image:
  repository: ghcr.io/semaforinformatik/intens-cloud-management-daemon
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# imageCredentials:
#   registry:
#   username:
#   password:

nameOverride: ""
fullnameOverride: ""

keycloak:
  enabled: true
  url:
  username:
  password: ""
  realm: ""

simpleTimeout:

configController:
  url: http://config-controller:3333

otel:
  enabled: false
  endpoint: http://grafana-k8s-monitoring-alloy.monitoring.svc.cluster.local:4318/v1/traces
